import Foundation

/// The primary implementation of the `APIGatewayProtocol`, executing HTTP requests to the backend API.
///
/// This class handles network communications for user authentication, token refresh, token revocation,
/// device integrity assertions, and security credentials issuance. It is bridged to Kotlin on Android via JNI.
public final class APIGateway: APIGatewayProtocol {

  private let executor: HTTPRequestExecutor

  /// Initializes a new `APIGateway` with custom configuration and HTTP client.
  ///
  /// - Parameters:
  ///   - configuration: The target API endpoint configuration.
  ///   - httpClient: The underlying network execution client.
  public init(
    configuration: GatewayConfiguration,
    httpClient: HTTPClient
  ) {
    self.executor = HTTPRequestExecutor(
      configuration: configuration,
      httpClient: httpClient
    )
  }

  /// Convenience initializer constructing the gateway from raw base URL and API version strings.
  ///
  /// - Parameters:
  ///   - baseURLString: The root URL string of the authentication backend server.
  ///   - apiVersion: The target backend API version string (e.g. "v1").
  /// - Throws: `GatewayError.invalidURL` if the base URL string is malformed.
  public convenience init(baseURLString: String, apiVersion: String) throws {
    guard let baseURL = URL(string: baseURLString) else {
      throw GatewayError.invalidURL(path: baseURLString)
    }

    self.init(
      configuration: GatewayConfiguration(baseURL: baseURL, apiVersion: apiVersion),
      httpClient: URLSessionHTTPClient()
    )
  }

  /// Fetches the backend server's public key utilized for client-side cryptographic payload verification.
  ///
  /// - Returns: A `ServerPublicKeyResponse` containing the server's public key.
  /// - Throws: `GatewayError` if the request fails or is rejected.
  public func serverPublicKey() async throws -> ServerPublicKeyResponse {
    try await executor.get(path: APIConstants.Auth.serverPublicKey)
  }

  /// Begins the OAuth 2.0 flow by registering code challenges and nonces with the backend.
  ///
  /// - Parameter request: The begin OAuth parameters.
  /// - Returns: The authentication URL and verification state.
  /// - Throws: `GatewayError` if the request fails.
  public func beginOAuth(request: OAuthBeginRequest) async throws -> OAuthBeginResponse {
    try await executor.post(path: APIConstants.Auth.oauthBegin, body: request)
  }

  /// Completes the OAuth 2.0 flow by exchanging identity tokens and device integrity assertions for active session tokens.
  ///
  /// - Parameter request: The completed OAuth payload and device parameters.
  /// - Returns: The backend response containing session tokens and user identifiers.
  /// - Throws: `GatewayError` if verification fails.
  public func completeOAuth(request: OAuthCompleteRequest) async throws -> OAuthCompleteResponse {
    try await executor.post(path: APIConstants.Auth.oauthComplete, body: request)
  }

  /// Refreshes the active access token using a refresh token.
  ///
  /// - Parameters:
  ///   - request: The token refresh request payload.
  ///   - accessToken: The active access token for authorization.
  /// - Returns: A new access and refresh token pair.
  /// - Throws: `GatewayError` if token rotation fails.
  public func refresh(
    request: RefreshRequest,
    accessToken: String
  ) async throws -> RefreshResponse {
    try await executor.post(
      path: APIConstants.Auth.refresh,
      body: request,
      accessToken: accessToken
    )
  }

  /// Revokes the current session access token.
  ///
  /// - Parameter accessToken: The access token to revoke.
  /// - Throws: `GatewayError` if revocation request fails.
  public func revoke(accessToken: String) async throws {
    try await executor.postVoid(
      path: APIConstants.Auth.revoke,
      accessToken: accessToken
    )
  }

  /// Submits a standalone device integrity assertion challenge verification to the backend.
  ///
  /// - Parameters:
  ///   - request: The integrity request payload including assertion data.
  ///   - accessToken: The active authorization access token.
  ///   - deviceProvider: The name of the integrity provider (e.g. apple_app_attest, play_integrity).
  ///   - requestNonce: One-time challenge nonce generated by the backend.
  ///   - requestTimestamp: Current ISO or millisecond timestamp.
  /// - Throws: `GatewayError` if validation fails.
  public func assertIntegrity(
    request: IntegrityRequest,
    accessToken: String,
    deviceProvider: String,
    requestNonce: String,
    requestTimestamp: String
  ) async throws {
    try await executor.postVoid(
      path: APIConstants.Auth.integrity,
      body: request,
      accessToken: accessToken,
      deviceHeaders: DeviceHeaders(
        provider: deviceProvider,
        nonce: requestNonce,
        timestamp: requestTimestamp
      )
    )
  }

  /// Requests a signed security credential payload bound to the device's local proof public key.
  ///
  /// - Parameters:
  ///   - request: The credential request payload.
  ///   - accessToken: The authorization access token.
  ///   - deviceProvider: The name of the integrity provider.
  ///   - requestNonce: The verification nonce.
  ///   - requestTimestamp: Current ISO or millisecond timestamp.
  /// - Returns: A signed `DeviceCredential` structure.
  /// - Throws: `GatewayError` if verification fails.
  public func issueCredential(
    request: CredentialRequest,
    accessToken: String,
    deviceProvider: String,
    requestNonce: String,
    requestTimestamp: String
  ) async throws -> DeviceCredential {
    try await executor.post(
      path: APIConstants.Auth.credential,
      body: request,
      accessToken: accessToken,
      deviceHeaders: DeviceHeaders(
        provider: deviceProvider,
        nonce: requestNonce,
        timestamp: requestTimestamp
      )
    )
  }

  /// Binds a zkLogin-derived Sui address to the authenticated user on the backend.
  ///
  /// - Parameters:
  ///   - request: The bind wallet parameters containing the sui address.
  ///   - accessToken: The active authorization access token.
  /// - Throws: `GatewayError` if the binding request fails.
  public func bindWallet(
    request: BindWalletRequest,
    accessToken: String
  ) async throws {
    try await executor.putVoid(
      path: APIConstants.Me.wallet,
      body: request,
      accessToken: accessToken
    )
  }

  /// Retrieves the authenticated user's profile metadata.
  ///
  /// - Parameter accessToken: The active authorization access token.
  /// - Returns: A `UserProfileResponse` containing user details.
  /// - Throws: `GatewayError` if the request fails.
  public func getProfile(accessToken: String) async throws -> UserProfileResponse {
    try await executor.get(
      path: APIConstants.Me.profile,
      accessToken: accessToken
    )
  }

  /// Uploads a binary avatar image for the user.
  ///
  /// - Parameters:
  ///   - data: The binary image data.
  ///   - contentType: The MIME content type (e.g. image/jpeg).
  ///   - accessToken: The active authorization access token.
  /// - Returns: A response containing the new avatar URL.
  /// - Throws: `GatewayError` if the upload fails.
  public func uploadAvatar(
    data: Data,
    contentType: String,
    accessToken: String
  ) async throws -> AvatarUploadResponse {
    try await executor.putRaw(
      path: APIConstants.Me.avatar,
      data: data,
      contentType: contentType,
      accessToken: accessToken
    )
  }

  /// Checks the availability of a leaf name under nearby.sui.
  ///
  /// - Parameters:
  ///   - leafName: The leaf name string to check.
  ///   - accessToken: The active authorization access token.
  /// - Returns: The name availability status.
  /// - Throws: `GatewayError` if the request fails.
  public func checkNameAvailability(
    leafName: String,
    accessToken: String
  ) async throws -> NameAvailabilityResponse {
    try await executor.get(
      path: APIConstants.Names.leafAvailable(name: leafName),
      accessToken: accessToken
    )
  }

  /// Submits an asynchronous request to register a leaf name under nearby.sui.
  ///
  /// - Parameters:
  ///   - request: The registration parameters containing the leaf name.
  ///   - accessToken: The active authorization access token.
  ///   - deviceProvider: The name of the device integrity provider.
  ///   - requestNonce: The verification nonce challenge.
  ///   - requestTimestamp: Current ISO or millisecond timestamp.
  /// - Returns: The registered task info.
  /// - Throws: `GatewayError` if registration fails.
  public func registerLeafName(
    request: RegisterLeafRequest,
    accessToken: String,
    deviceProvider: String,
    requestNonce: String,
    requestTimestamp: String
  ) async throws -> RegisterLeafResponse {
    try await executor.post(
      path: APIConstants.Names.leafRegister,
      body: request,
      accessToken: accessToken,
      deviceHeaders: DeviceHeaders(
        provider: deviceProvider,
        nonce: requestNonce,
        timestamp: requestTimestamp
      )
    )
  }

  /// Retrieves the current status of an asynchronous name registration task.
  ///
  /// - Parameters:
  ///   - taskId: The task identifier to query.
  ///   - accessToken: The active authorization access token.
  ///   - deviceProvider: The name of the device integrity provider.
  ///   - requestNonce: The verification nonce challenge.
  ///   - requestTimestamp: Current ISO or millisecond timestamp.
  /// - Returns: The current status of the task.
  /// - Throws: `GatewayError` if the request fails.
  public func getNameTask(
    taskId: String,
    accessToken: String,
    deviceProvider: String,
    requestNonce: String,
    requestTimestamp: String
  ) async throws -> NameTaskStatusResponse {
    try await executor.get(
      path: APIConstants.Names.taskStatus(id: taskId),
      accessToken: accessToken,
      deviceHeaders: DeviceHeaders(
        provider: deviceProvider,
        nonce: requestNonce,
        timestamp: requestTimestamp
      )
    )
  }
}
